/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* DiscoveryEventListener 
 * autogenerated from ../../include/equip_discovery_types.idl
 * by eqidl
 * DO NOT MODIFY
 */


package equip.discovery;

import equip.runtime.*;

/** callback interface for client discovery */
public abstract class DiscoveryEventListener extends ValueBase {

  /* lifecycle */
  public DiscoveryEventListener() {}

  /* member variables */
/** callback on discovery
       */
  public abstract void discoveryEvent(equip.discovery.DiscoveryClientAgent agent, String url);
/** callback on loss of previous discovery.
       * e.g. due to timeout or explicit removal.
       * Note that the information passed will in general not
       * be exactly the same object as was passed to discoveryEvent
       * (the references will not be equal using ==).
       */
  public abstract void discoveryRemoveEvent(equip.discovery.DiscoveryClientAgent agent, String url);
  /* helper routines */
  public String getModuleName() { return null; }
  public boolean equals(java.lang.Object c) {
    if (c==null) return false;
    if (!c.getClass().equals(getClass())) return false;
    return _equals_helper((DiscoveryEventListener)c);
  }
  public boolean _equals_helper(DiscoveryEventListener c) {
    if (c==null) return false;
    if (!super._equals_helper(c)) return false;
    return true;
  }
  public boolean matches(java.lang.Object c) {
    if (c==null || !(c instanceof DiscoveryEventListener)) return false;
    return _matches_helper((DiscoveryEventListener)c);
  }
  public boolean _matches_helper(DiscoveryEventListener c) {
    if (c==null) return false;
    if (!super._matches_helper(c)) return false;
    return true;
  }
  /* used by Object(In|Out)putStream only */
  public void writeObject(ObjectOutputStream out)
    throws java.io.IOException {
    out.writeObjectStart();
    out.writeObjectEnd();
  }
  public void readObject(ObjectInputStream in)
    throws java.io.IOException, ClassNotFoundException, 
      InstantiationException {
    in.readObjectStart();
    in.readObjectEnd();
  }


} /* class DiscoveryEventListener */

/* EOF */
