/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* DiscoveryEventListener 
 * initially autogenerated from ../../include/equip_discovery_types.idl
 * by eqidl
 */


package equip.discovery;

import equip.runtime.*;

public class DiscoveryEventListenerImpl extends DiscoveryEventListener {
  /* lifecycle */
  public DiscoveryEventListenerImpl() {
    //....
  }

  /* API */
/** callback on discovery
       */
  public void discoveryEvent(DiscoveryClientAgent agent, String info) {
    //....
    return;
  }
/** callback on loss of previous discovery.
       * e.g. due to timeout or explicit removal.
       * Note that the information passed will in general not
       * be exactly the same object as was passed to discoveryEvent
       * (the references will not be equal using ==).
       */
  public void discoveryRemoveEvent(DiscoveryClientAgent agent, String info) {
    //....
    return;
  }
  /* subclasses....*/


} /* class DiscoveryEventListener */

/* EOF */
