/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* DiscoveryRequest 
 * autogenerated from ../../include/equip_discovery_types.idl
 * by eqidl
 * DO NOT MODIFY
 */


package equip.discovery;

import equip.runtime.*;

/** Discovery request is this serialised into a multicast packet.
     * 
     * Based in part on JINI multicast discovery request.
     *
     * Service Type (extra cf JINI since we are not just looking for
     * lookup services) has common form 
     * "<interface-class-name>:<version-identifier>".
     * 
     * As in JINI (and SNMP), groups are strings which must match
     * exactly to identify common communities of action. E.g. to 
     * support concurrently deployment of different versions of the 
     * system.
     */
public abstract class DiscoveryRequest extends ValueBase {

  /* lifecycle */
  public DiscoveryRequest() {}

  /* member variables */
/** discovery protocol version - will be encoded before object *//** UDP port to send responses to */
  public short port;
/** type(s) of services solicited */
  public String serviceTypes[] = new String [0];
/** group(s) of services solicited */
  public String groups[] = new String [0];
/** service URLs already known */
  public String heard[] = new String [0];
  /* helper routines */
  public String getModuleName() { return null; }
  public boolean equals(java.lang.Object c) {
    if (c==null) return false;
    if (!c.getClass().equals(getClass())) return false;
    return _equals_helper((DiscoveryRequest)c);
  }
  public boolean _equals_helper(DiscoveryRequest c) {
    if (c==null) return false;
    if (!super._equals_helper(c)) return false;
    if(c.port != port) return false;
    if (c.serviceTypes==null || serviceTypes==null || c.serviceTypes.length!=serviceTypes.length) return false;
    int i1;
    for (i1=0; i1<serviceTypes.length; i1++) {
      if(serviceTypes[i1]!=c.serviceTypes[i1] && (serviceTypes[i1]==null || c.serviceTypes[i1] == null || !serviceTypes[i1].equals(c.serviceTypes[i1]))) return false;
    }
    if (c.groups==null || groups==null || c.groups.length!=groups.length) return false;
    for (i1=0; i1<groups.length; i1++) {
      if(groups[i1]!=c.groups[i1] && (groups[i1]==null || c.groups[i1] == null || !groups[i1].equals(c.groups[i1]))) return false;
    }
    if (c.heard==null || heard==null || c.heard.length!=heard.length) return false;
    for (i1=0; i1<heard.length; i1++) {
      if(heard[i1]!=c.heard[i1] && (heard[i1]==null || c.heard[i1] == null || !heard[i1].equals(c.heard[i1]))) return false;
    }
    return true;
  }
  public boolean matches(java.lang.Object c) {
    if (c==null || !(c instanceof DiscoveryRequest)) return false;
    return _matches_helper((DiscoveryRequest)c);
  }
  public boolean _matches_helper(DiscoveryRequest c) {
    if (c==null) return false;
    if (!super._matches_helper(c)) return false;
    if(c.port != port) return false;
    if (serviceTypes!=null && serviceTypes.length!=0 && (c.serviceTypes==null || c.serviceTypes.length!=serviceTypes.length)) return false;
    int i1;
    for (i1=0; i1<serviceTypes.length; i1++) {
      if(serviceTypes[i1]!=null && (c.serviceTypes[i1] == null || !serviceTypes[i1].equals(c.serviceTypes[i1]))) return false;
    }
    if (groups!=null && groups.length!=0 && (c.groups==null || c.groups.length!=groups.length)) return false;
    for (i1=0; i1<groups.length; i1++) {
      if(groups[i1]!=null && (c.groups[i1] == null || !groups[i1].equals(c.groups[i1]))) return false;
    }
    if (heard!=null && heard.length!=0 && (c.heard==null || c.heard.length!=heard.length)) return false;
    for (i1=0; i1<heard.length; i1++) {
      if(heard[i1]!=null && (c.heard[i1] == null || !heard[i1].equals(c.heard[i1]))) return false;
    }
    return true;
  }
  /* used by Object(In|Out)putStream only */
  public void writeObject(ObjectOutputStream out)
    throws java.io.IOException {
    out.writeObjectStart();
    out.writeShort(port);
    out.writeInt(serviceTypes.length);
    int i1;
    for (i1=0; i1<serviceTypes.length; i1++) {
      out.writeString(serviceTypes[i1]);
    }
    out.writeInt(groups.length);
    for (i1=0; i1<groups.length; i1++) {
      out.writeString(groups[i1]);
    }
    out.writeInt(heard.length);
    for (i1=0; i1<heard.length; i1++) {
      out.writeString(heard[i1]);
    }
    out.writeObjectEnd();
  }
  public void readObject(ObjectInputStream in)
    throws java.io.IOException, ClassNotFoundException, 
      InstantiationException {
    in.readObjectStart();
    port = in.readShort();
    { int len=0;
      len = in.readInt();
      serviceTypes = new String [len];
    }
    int i1;
    for (i1=0; i1<serviceTypes.length; i1++) {
      serviceTypes[i1] = in.readString();
    }
    { int len=0;
      len = in.readInt();
      groups = new String [len];
    }
    for (i1=0; i1<groups.length; i1++) {
      groups[i1] = in.readString();
    }
    { int len=0;
      len = in.readInt();
      heard = new String [len];
    }
    for (i1=0; i1<heard.length; i1++) {
      heard[i1] = in.readString();
    }
    in.readObjectEnd();
  }


} /* class DiscoveryRequest */

/* EOF */
