/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* ServerDiscoveryInfo 
 * autogenerated from ../../include/equip_discovery_types.idl
 * by eqidl
 * DO NOT MODIFY
 */


package equip.discovery;

import equip.runtime.*;

/** information on a single service.
     *
     * See DiscoveryRequest for into on service type and group.
     */
public abstract class ServerDiscoveryInfo extends ValueBase {

  /* lifecycle */
  public ServerDiscoveryInfo() {}

  /* member variables */
/** service type - see DiscoveryRequest */
  public String serviceTypes[] = new String [0];
/** group - see DiscoveryRequest */
  public String groups[] = new String [0];
/** server end point URL(s) */
  public String urls[] = new String [0];
  /* helper routines */
  public String getModuleName() { return null; }
  public boolean equals(java.lang.Object c) {
    if (c==null) return false;
    if (!c.getClass().equals(getClass())) return false;
    return _equals_helper((ServerDiscoveryInfo)c);
  }
  public boolean _equals_helper(ServerDiscoveryInfo c) {
    if (c==null) return false;
    if (!super._equals_helper(c)) return false;
    if (c.serviceTypes==null || serviceTypes==null || c.serviceTypes.length!=serviceTypes.length) return false;
    int i1;
    for (i1=0; i1<serviceTypes.length; i1++) {
      if(serviceTypes[i1]!=c.serviceTypes[i1] && (serviceTypes[i1]==null || c.serviceTypes[i1] == null || !serviceTypes[i1].equals(c.serviceTypes[i1]))) return false;
    }
    if (c.groups==null || groups==null || c.groups.length!=groups.length) return false;
    for (i1=0; i1<groups.length; i1++) {
      if(groups[i1]!=c.groups[i1] && (groups[i1]==null || c.groups[i1] == null || !groups[i1].equals(c.groups[i1]))) return false;
    }
    if (c.urls==null || urls==null || c.urls.length!=urls.length) return false;
    for (i1=0; i1<urls.length; i1++) {
      if(urls[i1]!=c.urls[i1] && (urls[i1]==null || c.urls[i1] == null || !urls[i1].equals(c.urls[i1]))) return false;
    }
    return true;
  }
  public boolean matches(java.lang.Object c) {
    if (c==null || !(c instanceof ServerDiscoveryInfo)) return false;
    return _matches_helper((ServerDiscoveryInfo)c);
  }
  public boolean _matches_helper(ServerDiscoveryInfo c) {
    if (c==null) return false;
    if (!super._matches_helper(c)) return false;
    if (serviceTypes!=null && serviceTypes.length!=0 && (c.serviceTypes==null || c.serviceTypes.length!=serviceTypes.length)) return false;
    int i1;
    for (i1=0; i1<serviceTypes.length; i1++) {
      if(serviceTypes[i1]!=null && (c.serviceTypes[i1] == null || !serviceTypes[i1].equals(c.serviceTypes[i1]))) return false;
    }
    if (groups!=null && groups.length!=0 && (c.groups==null || c.groups.length!=groups.length)) return false;
    for (i1=0; i1<groups.length; i1++) {
      if(groups[i1]!=null && (c.groups[i1] == null || !groups[i1].equals(c.groups[i1]))) return false;
    }
    if (urls!=null && urls.length!=0 && (c.urls==null || c.urls.length!=urls.length)) return false;
    for (i1=0; i1<urls.length; i1++) {
      if(urls[i1]!=null && (c.urls[i1] == null || !urls[i1].equals(c.urls[i1]))) return false;
    }
    return true;
  }
  /* used by Object(In|Out)putStream only */
  public void writeObject(ObjectOutputStream out)
    throws java.io.IOException {
    out.writeObjectStart();
    out.writeInt(serviceTypes.length);
    int i1;
    for (i1=0; i1<serviceTypes.length; i1++) {
      out.writeString(serviceTypes[i1]);
    }
    out.writeInt(groups.length);
    for (i1=0; i1<groups.length; i1++) {
      out.writeString(groups[i1]);
    }
    out.writeInt(urls.length);
    for (i1=0; i1<urls.length; i1++) {
      out.writeString(urls[i1]);
    }
    out.writeObjectEnd();
  }
  public void readObject(ObjectInputStream in)
    throws java.io.IOException, ClassNotFoundException, 
      InstantiationException {
    in.readObjectStart();
    { int len=0;
      len = in.readInt();
      serviceTypes = new String [len];
    }
    int i1;
    for (i1=0; i1<serviceTypes.length; i1++) {
      serviceTypes[i1] = in.readString();
    }
    { int len=0;
      len = in.readInt();
      groups = new String [len];
    }
    for (i1=0; i1<groups.length; i1++) {
      groups[i1] = in.readString();
    }
    { int len=0;
      len = in.readInt();
      urls = new String [len];
    }
    for (i1=0; i1<urls.length; i1++) {
      urls[i1] = in.readString();
    }
    in.readObjectEnd();
  }


} /* class ServerDiscoveryInfo */

/* EOF */
