/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* StatusValues 
 * autogenerated from ../../include/eqCoreTypes.idl
 * by eqidl
 * DO NOT MODIFY
 */


package equip.runtime;

import equip.runtime.*;

/**
     * General operation status code - 0 = OK wherever possible
     * (IDL'd in eqCoreTypes.idl).
     *
     * Exceptions are not currently (May 2002) used in EQUIP for the
     * most part; rather return status codes are used. This is the 
     * main status code enumeration, although they are no necessarily
     * used in a very precise way.<P>
     *
     * Some values and ideas are inherited from MASSIVE3 (e.g.
     * STATUS_CONTROL) and not necessary used in EQUIP, at least for
     * now.<P>
     * 
     * NOTES:
     * <ul>
     *
     * <li>STATUS_PARTIAL means it may work if you try again.
     *
     * <li>STATUS_PREMATURE_END typically signals an end of stream on
     * read.  
     *
     * </ul> */
public class StatusValues {
/** no error */
  public static final int STATUS_OK = 0;
/** data partially read; may work if you try again */
  public static final int STATUS_PARTIAL = 1;
/** operation failed completely (generic error) */
  public static final int STATUS_ERROR = 2;
/** syntax error */
  public static final int STATUS_SYNTAX_ERROR = 3;
/** file (or whatever) ended when more was expected */
  public static final int STATUS_PREMATURE_END = 4;
/** request failed due to access control */
  public static final int STATUS_NOT_OWNER = 5;
/** request refused */
  public static final int STATUS_REFUSED = 6;
/** request could not be performed at the current time */
  public static final int STATUS_NOT_YET = 7;
/** can't remember */
  public static final int STATUS_IGNORE = 8;
/** MASSIVE-3 status meaning that an indirect request to the
       * current owner might succeed */
  public static final int STATUS_CONTROLLED = 9;
/** request timed out */
  public static final int STATUS_TIMEDOUT = 10;
}
/* EOF */
