/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* DataSession 
 * autogenerated from common/idl/eqDataTypes.idl
 * by eqidl
 * DO NOT MODIFY
 */


package equip.data;

import equip.runtime.*;

/** The interface used to register {@link EventPattern}s with
     * a dataspace replica.
     *
     * All events from a single {@link DataSession} will be delivered
     * to the single {@link DataCallback} or {@link
     * DataCallbackPost} provided when the session was created.<P>
     *
     * <b>Note:</b> always use {@link DataProxy#createSession} to get
     * a data session. */
public abstract class DataSession extends ValueBase {

  /** Default no-arg constructor */
  public DataSession() {}

  /* member variables */
/** internal - the callback {@link DataCallback} or {@link
       * DataCallbackPost} */
  public equip.data.DataCallback callback;
/** internal - the callback closure */
  public equip.runtime.ValueBase closure;
/** internal - the callback pattern of interest */
  public equip.data.EventPattern patterns[] = new equip.data.EventPattern [0];
/** Add a new {@link EventPattern} to this session.
       *
       * Generates synchronous callbacks for local items. 
       *
       * @param pattern The new event pattern of interest. */
  public abstract void addPattern(equip.data.EventPattern pattern);
/** Add multiple new {@link EventPattern}s to this session.
       *
       * Generates synchronous callbacks for local items. 
       *
       * @param patterns The new event patterns of interest. */
  public abstract void addPatterns(equip.data.EventPattern []patterns);
/** Delete a previously added {@link EventPattern} from this
       * session as identified by its GUID.
       *
       * Generates synchronous callbacks for local items. 
       *
       * @param id The old event pattern's id. */
  public abstract void deletePattern(equip.data.GUID id);
/** Delete multiple previously added {@link EventPattern}s from
       * this session as identified by their GUIDs.
       *
       * Generates synchronous callbacks for local items. 
       *
       * @param ids The old event patterns' ids. */
  public abstract void deletePatterns(equip.data.GUID []ids);
/** Helper API: get a current pattern by GUID (if present).
       *
       * @param id The event pattern's id.
       * @return The matching {@link EventPattern} item registered
       * in this session, else <code>null</code>. */
  public abstract equip.data.EventPattern getPattern(equip.data.GUID id);
  /** IDL-generated helper routine to get module name (currently <b>unimplemented</b>).
  * @return name of this class's module
  */
  public String getModuleName() { return null; }
  /** Standard IDL-generated equality test.
  * @param c The object to be compared against this.
  * @return true if this is equal to <code>c</code>
  */
  public boolean equals(java.lang.Object c) {
    if (c==null) return false;
    if (!c.getClass().equals(getClass())) return false;
    return _equals_helper((DataSession)c);
  }
  /** Internal IDL-generated equality test helper */
  public boolean _equals_helper(DataSession c) {
    if (c==null) return false;
    if (!super._equals_helper(c)) return false;
    if (callback!=c.callback && (callback==null || !callback.equals(c.callback))) return false;
    if (closure!=c.closure && (closure==null || !closure.equals(c.closure))) return false;
    if (c.patterns==null || patterns==null || c.patterns.length!=patterns.length) return false;
    int i1;
    for (i1=0; i1<patterns.length; i1++) {
      if (patterns[i1]!=c.patterns[i1] && (patterns[i1]==null || !patterns[i1].equals(c.patterns[i1]))) return false;
    }
    return true;
  }
  /** Standard IDL-generated template match test. 
  * @param c The object to be checked against this template.
  * @return true if <code>this</code> (as a template) matches the argument
  */
  public boolean matches(java.lang.Object c) {
    if (c==null || !(c instanceof DataSession)) return false;
    return _matches_helper((DataSession)c);
  }
  /** Internal IDL-generated match test helper */
  public boolean _matches_helper(DataSession c) {
    if (c==null) return false;
    if (!super._matches_helper(c)) return false;
    if (callback!=null && !callback.matches(c.callback)) return false;
    if (closure!=null && !closure.matches(c.closure)) return false;
    if (patterns!=null && patterns.length!=0 && (c.patterns==null || c.patterns.length!=patterns.length)) return false;
    int i1;
    for (i1=0; i1<patterns.length; i1++) {
      if (patterns[i1]!=null && !patterns[i1].matches(c.patterns[i1])) return false;
    }
    return true;
  }
  /** Internal IDL-generated serialisation helper. Used by {@link equip.runtime.ObjectInputStream} and {@link equip.runtime.ObjectOutputStream} only. */
  public void writeObject(ObjectOutputStream out)
    throws java.io.IOException {
    out.writeObjectStart();
    out.writeObject(callback);
    out.writeObject(closure);
    out.writeInt(patterns.length);
    int i1;
    for (i1=0; i1<patterns.length; i1++) {
      out.writeObject(patterns[i1]);
    }
    out.writeObjectEnd();
  }
  /** Internal IDL-generated serialisation helper. Used by {@link ObjectInputStream} and {@link ObjectOutputStream} only. */
  public void readObject(ObjectInputStream in)
    throws java.io.IOException, ClassNotFoundException, 
      InstantiationException {
    in.readObjectStart();
    callback = (equip.data.DataCallback )in.readObject();
    closure = (equip.runtime.ValueBase )in.readObject();
    { int len=0;
      len = in.readInt();
      patterns = new equip.data.EventPattern [len];
    }
    int i1;
    for (i1=0; i1<patterns.length; i1++) {
      patterns[i1] = (equip.data.EventPattern )in.readObject();
    }
    in.readObjectEnd();
  }


} /* class DataSession */

/* EOF */
