/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* EventMetadata 
 * autogenerated from common/idl/eqDataTypes.idl
 * by eqidl
 * DO NOT MODIFY
 */


package equip.data;

import equip.runtime.*;

/** metadata for a dataspace {@link Event} */
public abstract class EventMetadata extends ValueBase {

  /** Default no-arg constructor */
  public EventMetadata() {}

  /* member variables */
/** the time at which the event was created */
  public equip.runtime.Time timestamp;
/** the GUID of the code fragment generating the event */
  public equip.data.GUID requestor;
/** used internally in event routing (the origin dataspace
       * replica) */
  public equip.data.GUID source;
/** whether the event should be kept within the local dataspace
       * replica */
  public boolean local;
/** whether the event should be distributed reliably.
       *
       * An unreliable event might be dropped by a communication
       * protocol or dropped from a dataspace internal queue of
       * similar events ('squashed'). */
  public boolean reliable;
/** Event priority, which may cause reordering in some
       * communications protocols (e.g. JCP).  
       *
       * priority defaults to 0; larger value = higher priority  */
  public int priority;
/** initialisation helper */
  public abstract void init2(equip.data.GUID agentId, boolean local, boolean reliable, int priority);
/** initialisation helper, default to priority 0 */
  public abstract void init(equip.data.GUID agentId, boolean local, boolean reliable);
  /** IDL-generated helper routine to get module name (currently <b>unimplemented</b>).
  * @return name of this class's module
  */
  public String getModuleName() { return null; }
  /** Standard IDL-generated equality test.
  * @param c The object to be compared against this.
  * @return true if this is equal to <code>c</code>
  */
  public boolean equals(java.lang.Object c) {
    if (c==null) return false;
    if (!c.getClass().equals(getClass())) return false;
    return _equals_helper((EventMetadata)c);
  }
  /** Internal IDL-generated equality test helper */
  public boolean _equals_helper(EventMetadata c) {
    if (c==null) return false;
    if (!super._equals_helper(c)) return false;
    if (timestamp!=c.timestamp && (timestamp==null || !timestamp.equals(c.timestamp))) return false;
    if (requestor!=c.requestor && (requestor==null || !requestor.equals(c.requestor))) return false;
    if (source!=c.source && (source==null || !source.equals(c.source))) return false;
    if(c.local != local) return false;
    if(c.reliable != reliable) return false;
    if(c.priority != priority) return false;
    return true;
  }
  /** Standard IDL-generated template match test. 
  * @param c The object to be checked against this template.
  * @return true if <code>this</code> (as a template) matches the argument
  */
  public boolean matches(java.lang.Object c) {
    if (c==null || !(c instanceof EventMetadata)) return false;
    return _matches_helper((EventMetadata)c);
  }
  /** Internal IDL-generated match test helper */
  public boolean _matches_helper(EventMetadata c) {
    if (c==null) return false;
    if (!super._matches_helper(c)) return false;
    if (timestamp!=null && !timestamp.matches(c.timestamp)) return false;
    if (requestor!=null && !requestor.matches(c.requestor)) return false;
    if (source!=null && !source.matches(c.source)) return false;
    if(c.local != local) return false;
    if(c.reliable != reliable) return false;
    if(c.priority != priority) return false;
    return true;
  }
  /** Internal IDL-generated serialisation helper. Used by {@link equip.runtime.ObjectInputStream} and {@link equip.runtime.ObjectOutputStream} only. */
  public void writeObject(ObjectOutputStream out)
    throws java.io.IOException {
    out.writeObjectStart();
    out.writeObject(timestamp);
    out.writeObject(requestor);
    out.writeObject(source);
    out.writeBoolean(local);
    out.writeBoolean(reliable);
    out.writeInt(priority);
    out.writeObjectEnd();
  }
  /** Internal IDL-generated serialisation helper. Used by {@link ObjectInputStream} and {@link ObjectOutputStream} only. */
  public void readObject(ObjectInputStream in)
    throws java.io.IOException, ClassNotFoundException, 
      InstantiationException {
    in.readObjectStart();
    timestamp = (equip.runtime.Time )in.readObject();
    requestor = (equip.data.GUID )in.readObject();
    source = (equip.data.GUID )in.readObject();
    local = in.readBoolean();
    reliable = in.readBoolean();
    priority = in.readInt();
    in.readObjectEnd();
  }


} /* class EventMetadata */

/* EOF */
