/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* GUIDFactory 
 * autogenerated from ../../include/eqDataTypes.idl
 * by eqidl
 * DO NOT MODIFY
 */


package equip.data;

import equip.runtime.*;
import java.net.*;
import equip.net.*;

/** The concrete implementation of the IDL'd GUID factory class {@link
 * GUIDFactory}. It is recommended to use {@link
 * equip.runtime.SingletonManager} to get a per-process instance of
 * this class. If you are using the {@link
 * equip.data.beans.IDataspace} API then you can use that instead. */
public class GUIDFactoryImpl extends GUIDFactory {
    private ServerSocket socket;
    private int host;
    private int port;
    private int next_item_id;
    private int time_s;

    /* lifecycle */
    public GUIDFactoryImpl() {
	port = 0;
	try {
	    socket = new ServerSocket(0);
	    port = socket.getLocalPort();
	} catch (Exception e) {
	    System.err.println("ERROR: GUIDFactoryImpl unable to open "+
			       "server socket - GUIDs will be broken");
	}   
	SimpleTCPMoniker mon = new SimpleTCPMonikerImpl();
	mon.initFromPort((short)port);
	host = mon.addr;
	next_item_id = 0;
	Time now = new TimeImpl();
	now.getCurrentTime();
	time_s = now.sec;
    }

    /* API */
    public GUID getUnique() {
	GUID id = new GUIDImpl();
	id.host_id = host;
	id.proc_id = ((int)port) & 0xffff;
	// threads....
	synchronized(this) {
	    id.item_id = next_item_id++;
	    if(next_item_id==0) {
		// update time 
		time_s++;
	    }
	    id.time_s = time_s; 
	}
	return id;
    }
    public GUID getNull() {
      GUID id = new GUIDImpl();
      id.host_id = 0;
      id.proc_id = 0;
      id.item_id =0;
      id.time_s = 0;
      return id;
    }
    /* subclasses....*/


} /* class GUIDFactory */

/* EOF */
