/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* SerializedObject 
 * autogenerated from ../../include/equip_data_tuple.idl
 * by eqidl
 * DO NOT MODIFY
 */


package equip.data;

import equip.runtime.*;

/** holder for a serialized native language object.
     * matching requires byte equality of serialisation. 
     */
public abstract class SerializedObject extends ValueBase {

  /** Default no-arg constructor */
  public SerializedObject() {}

  /* member variables */
/** serialization method used with this instance.
       * e.g. "java", "equip".
       * no point comparing if they differ, or trying to deserialize.
       */
  public String serializationMethod;
/** actual bytes of serialised data. */
  public byte data[] = new byte [0];
  /** IDL-generated helper routine to get module name (currently <b>unimplemented</b>).
  * @return name of this class's module
  */
  public String getModuleName() { return null; }
  /** Standard IDL-generated equality test.
  * @param c The object to be compared against this.
  * @return true if this is equal to <code>c</code>
  */
  public boolean equals(java.lang.Object c) {
    if (c==null) return false;
    if (!c.getClass().equals(getClass())) return false;
    return _equals_helper((SerializedObject)c);
  }
  /** Internal IDL-generated equality test helper */
  public boolean _equals_helper(SerializedObject c) {
    if (c==null) return false;
    if (!super._equals_helper(c)) return false;
    if(serializationMethod!=c.serializationMethod && (serializationMethod==null || c.serializationMethod == null || !serializationMethod.equals(c.serializationMethod))) return false;
    if (c.data==null || data==null || c.data.length!=data.length) return false;
    int i1;
    for (i1=0; i1<data.length; i1++) {
      if(c.data[i1] != data[i1]) return false;
    }
    return true;
  }
  /** Standard IDL-generated template match test. 
  * @param c The object to be checked against this template.
  * @return true if <code>this</code> (as a template) matches the argument
  */
  public boolean matches(java.lang.Object c) {
    if (c==null || !(c instanceof SerializedObject)) return false;
    return _matches_helper((SerializedObject)c);
  }
  /** Internal IDL-generated match test helper */
  public boolean _matches_helper(SerializedObject c) {
    if (c==null) return false;
    if (!super._matches_helper(c)) return false;
    if(serializationMethod!=null && (c.serializationMethod == null || !serializationMethod.equals(c.serializationMethod))) return false;
    if (data!=null && data.length!=0 && (c.data==null || c.data.length!=data.length)) return false;
    int i1;
    for (i1=0; i1<data.length; i1++) {
      if(c.data[i1] != data[i1]) return false;
    }
    return true;
  }
  /** Internal IDL-generated serialisation helper. Used by {@link equip.runtime.ObjectInputStream} and {@link equip.runtime.ObjectOutputStream} only. */
  public void writeObject(ObjectOutputStream out)
    throws java.io.IOException {
    out.writeObjectStart();
    out.writeString(serializationMethod);
    out.writeInt(data.length);
    if (data.length!=0)
      out.write(data,0,data.length);
    out.writeObjectEnd();
  }
  /** Internal IDL-generated serialisation helper. Used by {@link ObjectInputStream} and {@link ObjectOutputStream} only. */
  public void readObject(ObjectInputStream in)
    throws java.io.IOException, ClassNotFoundException, 
      InstantiationException {
    in.readObjectStart();
    serializationMethod = in.readString();
    { int len=0;
      len = in.readInt();
      data = new byte [len];
    }
    if (data.length!=0) {
      if (in.read(data,0,data.length)!=data.length)
        throw new java.io.IOException("EOF in byte array");
    }
    in.readObjectEnd();
  }


} /* class SerializedObject */

/* EOF */
