/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* Tuple 
 * autogenerated from ../../include/equip_data_tuple.idl
 * by eqidl
 * DO NOT MODIFY
 */


package equip.data;

import equip.runtime.*;

/** The generic tuple type.
     *   Matches iff array of fields in template is no longer than
     * array of fields in value, and each field in the template is
     * null (wildcard) or matches the field value in the value
     * object.<P>
     *   Please use a StringBox as the first field to contain a 
     * nominal tuple pseudo-class name. To simulate sub-class
     * matching make this the top-most superclass; include sub-class
     * names as StringBox fields after gaps for superclass fields.
     * e.g. ["superclass","field1","field2","subclass","field3"]
     * will match ["superclass","field1","field2"].<P>
     */
public abstract class Tuple extends equip.data.ItemData {

  /** Default no-arg constructor */
  public Tuple() {}

  /* member variables */
/** array of fields */
  public equip.runtime.ValueBase fields[] = new equip.runtime.ValueBase [0];
  /** IDL-generated helper routine to get module name (currently <b>unimplemented</b>).
  * @return name of this class's module
  */
  public String getModuleName() { return null; }
  /** Standard IDL-generated equality test.
  * @param c The object to be compared against this.
  * @return true if this is equal to <code>c</code>
  */
  public boolean equals(java.lang.Object c) {
    if (c==null) return false;
    if (!c.getClass().equals(getClass())) return false;
    return _equals_helper((Tuple)c);
  }
  /** Internal IDL-generated equality test helper */
  public boolean _equals_helper(Tuple c) {
    if (c==null) return false;
    if (!super._equals_helper(c)) return false;
    if (c.fields==null || fields==null || c.fields.length!=fields.length) return false;
    int i1;
    for (i1=0; i1<fields.length; i1++) {
      if (fields[i1]!=c.fields[i1] && (fields[i1]==null || !fields[i1].equals(c.fields[i1]))) return false;
    }
    return true;
  }
  /** Standard IDL-generated template match test. 
  * @param c The object to be checked against this template.
  * @return true if <code>this</code> (as a template) matches the argument
  */
  public boolean matches(java.lang.Object c) {
    if (c==null || !(c instanceof Tuple)) return false;
    return _matches_helper((Tuple)c);
  }
  /** Internal IDL-generated match test helper */
  public boolean _matches_helper(Tuple c) {
    if (c==null) return false;
    if (!super._matches_helper(c)) return false;
    if (fields!=null && fields.length!=0 && (c.fields==null || c.fields.length!=fields.length)) return false;
    int i1;
    for (i1=0; i1<fields.length; i1++) {
      if (fields[i1]!=null && !fields[i1].matches(c.fields[i1])) return false;
    }
    return true;
  }
  /** Internal IDL-generated serialisation helper. Used by {@link equip.runtime.ObjectInputStream} and {@link equip.runtime.ObjectOutputStream} only. */
  public void writeObject(ObjectOutputStream out)
    throws java.io.IOException {
    super.writeObject(out);
    out.writeObjectStart();
    out.writeInt(fields.length);
    int i1;
    for (i1=0; i1<fields.length; i1++) {
      out.writeObject(fields[i1]);
    }
    out.writeObjectEnd();
  }
  /** Internal IDL-generated serialisation helper. Used by {@link ObjectInputStream} and {@link ObjectOutputStream} only. */
  public void readObject(ObjectInputStream in)
    throws java.io.IOException, ClassNotFoundException, 
      InstantiationException {
    super.readObject(in);
    in.readObjectStart();
    { int len=0;
      len = in.readInt();
      fields = new equip.runtime.ValueBase [len];
    }
    int i1;
    for (i1=0; i1<fields.length; i1++) {
      fields[i1] = (equip.runtime.ValueBase )in.readObject();
    }
    in.readObjectEnd();
  }


} /* class Tuple */

/* EOF */
