/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* UpdateEvent 
 * autogenerated from common/idl/eqDataTypes.idl
 * by eqidl
 * DO NOT MODIFY
 */


package equip.data;

import equip.runtime.*;

/** An event representing the update of a previously added {@link
	ItemData} instance in the dataspace; replaces the previous
	item value with the new value in the event. Typically
	generated by calls to {@link DataProxy#updateItem}.  NOTE:
	UpdateEvents should not be created by the application for
	items with Leases; use an AddEvent instead (with the new Lease
	value in the ItemBinding).*/
public abstract class UpdateEvent extends equip.data.Event {

  /** Default no-arg constructor */
  public UpdateEvent() {}

  /* member variables */
/** The new item value (with the same id) */
  public equip.data.ItemData item;
/** Initialisation helper; see {@link EventMetadata} for most
	  arguments. NB only UpdateEvent and MutateEvent encourage
	  unreliable events */
  public abstract void initFromItem2(equip.data.ItemData item, equip.data.GUID agentId, boolean local, boolean reliable, int priority);
/** Initialisation helper; see {@link EventMetadata} for most
	  arguments. NB only UpdateEvent and MutateEvent encourage
	  unreliable events */
  public abstract void initFromItem(equip.data.ItemData item, equip.data.GUID agentId, boolean local, boolean reliable);
  /** IDL-generated helper routine to get module name (currently <b>unimplemented</b>).
  * @return name of this class's module
  */
  public String getModuleName() { return null; }
  /** Standard IDL-generated equality test.
  * @param c The object to be compared against this.
  * @return true if this is equal to <code>c</code>
  */
  public boolean equals(java.lang.Object c) {
    if (c==null) return false;
    if (!c.getClass().equals(getClass())) return false;
    return _equals_helper((UpdateEvent)c);
  }
  /** Internal IDL-generated equality test helper */
  public boolean _equals_helper(UpdateEvent c) {
    if (c==null) return false;
    if (!super._equals_helper(c)) return false;
    if (item!=c.item && (item==null || !item.equals(c.item))) return false;
    return true;
  }
  /** Standard IDL-generated template match test. 
  * @param c The object to be checked against this template.
  * @return true if <code>this</code> (as a template) matches the argument
  */
  public boolean matches(java.lang.Object c) {
    if (c==null || !(c instanceof UpdateEvent)) return false;
    return _matches_helper((UpdateEvent)c);
  }
  /** Internal IDL-generated match test helper */
  public boolean _matches_helper(UpdateEvent c) {
    if (c==null) return false;
    if (!super._matches_helper(c)) return false;
    if (item!=null && !item.matches(c.item)) return false;
    return true;
  }
  /** Internal IDL-generated serialisation helper. Used by {@link equip.runtime.ObjectInputStream} and {@link equip.runtime.ObjectOutputStream} only. */
  public void writeObject(ObjectOutputStream out)
    throws java.io.IOException {
    super.writeObject(out);
    out.writeObjectStart();
    out.writeObject(item);
    out.writeObjectEnd();
  }
  /** Internal IDL-generated serialisation helper. Used by {@link ObjectInputStream} and {@link ObjectOutputStream} only. */
  public void readObject(ObjectInputStream in)
    throws java.io.IOException, ClassNotFoundException, 
      InstantiationException {
    super.readObject(in);
    in.readObjectStart();
    item = (equip.data.ItemData )in.readObject();
    in.readObjectEnd();
  }


} /* class UpdateEvent */

/* EOF */
