/*
<COPYRIGHT>

Copyright (c) 2002-2005, University of Nottingham
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 - Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 - Neither the name of the University of Nottingham
   nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

</COPYRIGHT>

Created by: Chris Greenhalgh (University of Nottingham)
Contributors:
  Chris Greenhalgh (University of Nottingham)

*/
/* TraderMoniker 
 * autogenerated from ../../include/eqTraderTypes.idl
 * by eqidl
 * DO NOT MODIFY
 */


package equip.net;

import equip.runtime.*;

/** Implementation of IDL'd class {@link TraderMoniker} */
public class TraderMonikerImpl extends TraderMoniker {
  /* lifecycle */
  public TraderMonikerImpl() {
    //....
  }

    /* API */
    public boolean rebind(Moniker proxyMoniker) {
	System.err.println("TraderMonikerImpl::rebind...");
	TraderProxy proxy = new TraderProxyImpl();
	proxy.serviceMoniker = trader;
	if (!proxy.activate(null,null)) {
	    System.err.println("ERROR: could not activate trader proxy");
	    return false;
	}
	boolean ok = proxy.rebind(name, proxyMoniker);
	System.err.println((ok ? "OK" : "Failed"));
	return ok;
    }
    /* subclasses....*/


    /* subclass Moniker */
    public SimpleMoniker resolve() {
	System.err.println("TraderMonikerImpl::resolve...");
	TraderProxy proxy = new TraderProxyImpl();
	proxy.serviceMoniker = trader;
	if (!proxy.activate(null,null)) {
	    System.err.println("ERROR: could not activate trader proxy");
	    return null;
	}
	ValueBase reply = proxy.lookup(name, null);
	if (reply!=null && reply instanceof SimpleMoniker) {
	    SimpleMoniker smon = (SimpleMoniker)reply;
	    proxy.deactivate();
	    System.err.println("OK");
	    return smon;
	}
	if (reply==null) {
	    proxy.deactivate();
	    System.err.println("failed");
	    return null;
	}
	// recurse?
	if (reply instanceof Moniker) {
	    Moniker mon = (Moniker)reply;
	    // recurse
	    proxy.deactivate();
	    System.err.println("recurse...");
	    return mon.resolve();
	}
	// unknown type
	proxy.deactivate();
	System.err.println("ERROR: TraderMonikerImpl::resolve returned "+
			   "non-moniker: "+reply);
	return null;
    }
} /* class TraderMoniker */

/* EOF */
